export enum BoxColor {
    Blue = 'blue',
    Green = 'green',
    Red = 'red',
    Yellow = 'yellow',
    Gray = 'gray',
    Black = 'black',
    Orange = 'orange',
    Purple = 'purple',
    Pink = 'pink',
    Teal = 'teal',
    Indigo = 'indigo',
    Cyan = 'cyan',
    Transparent = 'transparent',
}
